title: Nava's page
author:
  name: Jesse Nava
  email: code@nava.xyz
description: >
  My experiences with functional programming.
  Hoping future me will revisit this and
  be happy to see how much progress was made! 

minima:
  social-links:
    github: j-nava

  skin: dark

header_pages:
  - index.md

theme: minima